//
//  Game.swift
//  In a Sheet of Paper
//
//  Created by ditthales on 17/04/23.
//

import SwiftUI

struct Game{
    let showImage: [Bool]
    let changeScreen: Bool
    let rotateLast: Bool
    let bottomText: String
    let baseImage: String
    let isVinsDraws: Bool
    let flipImage: Bool
}

extension Game{
    static var userDraws: [UIImage] = []
    static var currentIndex: Int = 0
    static func getGameInfos() -> [Game]{
        return [
            Game(showImage: [false, false, false, false, false, false, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "Hey, I know... you can't see anything. It's weird but you'll get used to it. I'm here to help you too, don't be afraid.",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, false, false, false, false, false, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "By the way, my name is Vin. Nice to meet you.",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, false, false, false, false, false, false, false, false],
                 changeScreen: true,
                 rotateLast: false,
                 bottomText: "First of all, I need to know how you look like. Draw it and press the 'Done' button when you finish!",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, false, false, false, false, false, false, false, false],
                 changeScreen: true,
                 rotateLast: false,
                 bottomText: "Draw your full body below looking to the right. For a better experience draw it inside the dashed area. Press the 'Done' button when you finish!",
                 baseImage: "dashed-person-block",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [true, false, false, false, false, false, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "Hey, you're looking great! Alright, it looks like we're in some sort of room. Let's explore it a bit.",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [true, false, false, false, false, false, false, false, false],
                 changeScreen: true,
                 rotateLast: false,
                 bottomText: "It seems there's something right in front of you, you can touch it, look! It seems to be a table with a thing on it... It's an object that exists in every home, a very popular item...",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [true, false, false, false, false, false, false, false, false],
                 changeScreen: true,
                 rotateLast: false,
                 bottomText: "What do you think is on this table? Imagine it below and press the 'Done' button when you finish!!",
                 baseImage: "table",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [true, true, true, false, false, false, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "This is really interesting, I like you! Let's walk a little more...",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, true, true, true, false, false, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "This is really interesting, I like you! Let's walk a little more...",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, true, true, true, false, false, false, false, false],
                 changeScreen: true,
                 rotateLast: false,
                 bottomText: "Oh! That’s new for us... It’s a pet! Oh it's so cute! Yeah, it's exactly that pet you're thinking of. The one that's in your heart. ",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, true, true, true, false, false, false, false, false],
                 changeScreen: true,
                 rotateLast: false,
                 bottomText: "Can you draw this pet for me? Imagine it below and press the 'Done' button when you finish! For a better experience draw it inside the dashed area.",
                 baseImage: "dashed-pet-block",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, true, true, true, true, false, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "It's so cute <3. Let's walk a little more...",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, true, true, false, true, true, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "It's so cute <3. Let's walk a little more...",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, true, true, false, true, true, false, false, false],
                 changeScreen: true,
                 rotateLast: false,
                 bottomText: "Now we have a painting in the wall. A painting that reminds you a lot of your childhood, your home, your land!",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, true, true, false, true, true, false, false, false],
                 changeScreen: true,
                 rotateLast: false,
                 bottomText: "What's in that painting? Imagine it below and press the 'Done' button when you finish!!",
                 baseImage: "painting-moldure",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, true, true, false, true, true, true, true, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "I can feel your emotions just seeing it. What a painting!",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, true, true, false, true, true, true, true, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "It looks like we're near the end of the room. Let's walk a little more!",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, true, true, false, true, false, true, true, true],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "It looks like we're near the end of the room. Let's walk a little more!",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, true, true, false, true, false, true, true, true],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "Wait! Before you leave, look back!",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, true, true, false, true, false, true, true, true],
                 changeScreen: false,
                 rotateLast: true,
                 bottomText: "Wait! Before you leave, look back!",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: true),
            Game(showImage: [false, true, true, false, true, false, true, true, true],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "Look at this scene. It's all yours! All of that came from your mind, that's really cool.",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: true),
            Game(showImage: [false, true, true, false, true, false, true, true, true],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "I would have never done it that way, it's your unique touch that you left around here.",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: true),
            Game(showImage: [false, true, true, false, true, false, true, true, true],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "Maybe you don't imagine, but I also couldn't see anything in this room. Both of us don't know how it is, but maybe it's better this way!",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: true),
            Game(showImage: [false, true, true, false, true, false, true, true, true],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "I'll show you how I thought it.",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: true),
            Game(showImage: [false, true, true, false, true, false, true, true, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "I'll show you how I thought it.",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: true),
            Game(showImage: [false, true, true, false, true, false, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "I'll show you how I thought it.",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, true, true, false, false, false, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "I'll show you how I thought it.",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [false, false, false, false, false, false, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "I'll show you how I thought it.",
                 baseImage: "",
                 isVinsDraws: false,
                 flipImage: false),
            Game(showImage: [true, false, false, false, false, false, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "This is me. As I said my name is Vin, I'm from northeastern Brazil. Hello!",
                 baseImage: "",
                 isVinsDraws: true,
                 flipImage: false),
            Game(showImage: [true, true, true, false, false, false, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "On this table we have a clay filter, a very common object especially in grandmothers' houses around here.",
                 baseImage: "",
                 isVinsDraws: true,
                 flipImage: false),
            Game(showImage: [false, true, true, true, false, false, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "...",
                 baseImage: "",
                 isVinsDraws: true,
                 flipImage: false),
            Game(showImage: [false, true, true, true, true, false, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "This is Luke, my mixed breed dog. I love him!",
                 baseImage: "",
                 isVinsDraws: true,
                 flipImage: false),
            Game(showImage: [false, true, true, false, true, true, false, false, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "...",
                 baseImage: "",
                 isVinsDraws: true,
                 flipImage: false),
            Game(showImage: [false, true, true, false, true, true, true, true, false],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "And this is a painting I made that is very representative of my region here in Brazil.",
                 baseImage: "",
                 isVinsDraws: true,
                 flipImage: false),
            Game(showImage: [false, true, true, false, true, false, true, true, true],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "...",
                 baseImage: "",
                 isVinsDraws: true,
                 flipImage: false),
            Game(showImage: [false, true, true, false, true, false, true, true, true],
                 changeScreen: false,
                 rotateLast: true,
                 bottomText: "...",
                 baseImage: "",
                 isVinsDraws: true,
                 flipImage: true),
            Game(showImage: [false, true, true, false, true, false, true, true, true],
                 changeScreen: false,
                 rotateLast: false,
                 bottomText: "Yeah, I'm really proud of what I've done too. Thank you for joining me on this journey.",
                 baseImage: "",
                 isVinsDraws: true,
                 flipImage: true),
            Game(showImage: [false, true, true, false, true, false, true, true, true],
                 changeScreen: true,
                 rotateLast: true,
                 bottomText: "Now we can turn on the lights!",
                 baseImage: "",
                 isVinsDraws: true,
                 flipImage: false),
            
            

            
            
            
        ]
    }
}
